print("What's the best part of old age?")
input()
print("That it doesn't last very long.")
print("------------------------------------------------")
print("Here comes another joke")
input()
print("what do you calla bear with no teeth?")
input()
print("A gummy bear")
print("------------------------------------------------")
print("And here's another joke")
input()
print("Why did the banana go to the doctor?")
input()
print("Because it wasn't pelling well.")

