name = input(" what is your name?")
print(f"Hello {name} and welcome to CT8")
print("Today we will be telling a story with your help ")
print("")
location = input("pick your favorite spot to eat: ")
friend = input("choose a friend")
print(f"On the weekend me and {friend} like to go to our favorite spot to eat {location}.")
print("")
print("Okay now we are going to do a second part of the story")
print("")
location_2 = input("pick your favorite place to go shopping at: ")
friend_2 = input("choose another friend:")
print(f" On the weekend me and {friend} like to go to our favorite spot to eat {location}, me and {friend_2} love to go shopping at {location_2} all the time.")
print("")
print("Thank you for making a story with me")
